### ISSUE TITLE
Completion event

### ISSUE THREAD

**Issue by barryjenkin** [mike-st/adapt-before-and-after#1]
Hi there. Nice component :)
I was hoping this would trigger completion once a user has fully revealed the after-image. Should this be happening already or is there a way to achieve this?

**Comment by mike-st** [comment]
Hi Barry thanks for the comments and feedback. Good point about triggering completion I had meant to put that in but got caught up in testing the responsive and accessibility modes. I have added a trigger state to the slider handle bar, so that when the user starts dragging it will initiate completion. I did this because the user starts with the bar in the middle and can freely go either way. So there is no real right or wrong way of viewing the before and after images.
